[package]
name = "type_inference"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "type inference for lazysql"

[dependencies]
pretty_assertions = "1.4.1"
sqlparser = {version = "0.59.0", features = ["visitor"]}
