[package]
name = "type_inference"
version = "0.1.0"
edition = "2024"
description = "type inference for lazysql"
license = "MIT"

[dependencies]
pretty_assertions = "1.4.1"
sqlparser = {version = "0.59.0", features = ["visitor"]}
