[package]
name = "lazysql-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "core logic for lazysql"


[dependencies]
libsqlite3-sys = {version = "0.35.0", features = ["bundled"]}
thiserror = "2.0.17"
type_inference.workspace = true