[package]
name = "lazysql-core"
version = "0.1.0"
edition = "2024"
description = "core logic for lazysql"
license = "MIT"


[dependencies]
libsqlite3-sys = "0.35.0"
thiserror = "2.0.17"
type_inference ={ path = "../type_inference", version = "0.1.0"}
